### STAGE 1
FROM node:18-alpine AS builder

WORKDIR /usr/src/app

COPY ./package.json ./

RUN npm install

COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build

### COPY INTO SECONDARY CADDY FILE
### STAGE 2

FROM caddy:2-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 80

EXPOSE 443
